### ISSUE TITLE
Payment additional_information is overwritten when adding a new order transaction

### ISSUE THREAD

**Issue by mattijv** [Verifone-NB/magento2-verifone-payment#4]
### System
- Magento 2.1.7
- Verifone_Payment 0.1.1

### Description
The addNewOrderTransaction method in Verifone\Payment\Helper\Order does the following call
```
$payment->setAdditionalInformation(
    [
        \Magento\Sales\Model\Order\Payment\Transaction::RAW_DETAILS =>
            [
                'payment-method' => $paymentMethod
            ]
    ]
);
```
Since the only argument to the setAdditionalInformation is an array, the method will overwrite any existing values in the additional_information field. Also the use of 
```
\Magento\Sales\Model\Order\Payment\Transaction::RAW_DETAILS
```
seems out of place and potentially confusing, since in Magento it apparently is only supposed to be used in the sales_payment_transaction table and associated models.

_I'm assuming the paymentMethod here is saved to the additional information because the actual method can be selected in the Verifone endpoint instead of the checkout page._

### Expected
- Payment method is saved into the additional_information without replacing all existing data.
- Payment method is saved with a sensible key, preferably namespaced to the module.

### Actual
- Payment method overwrites any data saved in the additional_information field by other modules.
- Payment method is saved under a confusing key.

**Comment by szymonnosal** [comment]
Fixed in newest release 0.1.2
