### ISSUE TITLE
Error in back-end config

### ISSUE THREAD

**Issue by kerlama** [Verifone-NB/magento2-verifone-payment#7]
Hi,
after installation on clean m 2.3.1 I get this when trying to access Store > Configuration > Payment Methods

Exception #0 (Exception): Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/vhosts/local/httpdocs/vendor/verifone/module-payment/src/Block/System/Config/Group/PaymentArray.php on line 94

Ivan

**Comment by szymonnosal** [comment]
Fixed with release 0.1.8
