### ISSUE TITLE
Return from Verifone fails with 'Invalid Form Key' error

### ISSUE THREAD

**Issue by mattijv** [Verifone-NB/magento2-verifone-payment#8]
## Description

After placing an order and supplying the payment details in the payment service the user is redirected back to the Magento store. This however currently fails in M2.3.2 with the user being redirected to the frontpage and displayed the following error message: 'Invalid Form Key. Please refresh the page.'

## Steps to reproduce
1. M2.3.2
2. Place and order and return to Magento from the payment service

### Expected result
Magento success page.

### Actual result
Redirected to the front page with the error 'Invalid Form Key. Please refresh the page.'.

## Possible reason
Magento 2.3 introduced the `CsrfValidator` which validates the presence and validity of the form_key param. Alternatively the action could implement the `CsrfAwareActionInterface` interface to provide a custom validation scheme.

The Verifone_Payment module _seems_ to take the csrf validation into account by setting the parameter `ajax` to `true` on the request if the abovementioned interface exists. It is however unclear to me how this is meant to get around the Magento Csrf validation. And it does not seem to work.

---

If it were possible to get an explanation on how setting the `ajax` to true is supposed to work with the validation, I could make sure that the issue is not caused by something else in our system.

**Comment by robertsplorins** [comment]
Yes, same happening for me in magento 2.3.2 
Looks like it's because of this change https://github.com/magento/magento2/commit/218527010e9587335d13096ae203ddf467783f2b

So maybe instead of modifying ajax parameter, should modify the X_REQUESTED_WITH header by setting 'XMLHttpRequest' value - so that this function returns true \Zend\Http\Request::isXmlHttpRequest

**Comment by mattijv** [comment]
@robertsplorins Thank you, I don't know how I missed that change when looking over how Magento has changed between versions. That would completely explain the issues we are facing since we are running on M2.3.2.

I was unable to locate any documentation on the API this module is working with, but if it supports something like return parameters, the best fix would be to submit the current `form_key` to the payment service and get them back in the request. This should make the request pass the `form_key` validation without any code needed.

If that is not possible then modifying the header will probably be the best solution.

**Comment by robertsplorins** [comment]
Btw here is the patch I Used to fix this 
```
--- src/Controller/AbstractPayment-orig.php	2019-09-27 17:15:21.000000000 +0300
+++ src/Controller/AbstractPayment.php	2019-09-27 17:23:02.000000000 +0300
@@ -71,7 +70,9 @@
         if(interface_exists("\Magento\Framework\App\CsrfAwareActionInterface")) {
             $request = $this->getRequest();
             if ($request instanceof Http && $request->isPost()) {
-                $request->setParam('ajax', true);
+                /** @var \Zend\Http\Headers $headers */
+                $headers = $request->getHeaders();
+                $headers->addHeaderLine('X_REQUESTED_WITH', 'XMLHttpRequest');
             }
         }
     }
@@ -83,7 +84,10 @@
         if(interface_exists("\Magento\Framework\App\CsrfAwareActionInterface")) {
             $request = $this->getRequest();
             if ($request instanceof Http && $request->isPost()) {
-                $request->setParam('ajax', null);
+                /** @var \Zend\Http\Headers $headers */
+                $headers = $request->getHeaders();
+                $header = $headers->get('X_REQUESTED_WITH');
+                $headers->removeHeader($header);
             }
         }
     }
```

**Comment by szymonnosal** [comment]
@robertsplorins thank you for the patch.
